# Generated by Django 3.0 on 2020-02-29 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'Rent'), ('S', 'Sale')], max_length=2)),
                ('image', models.ImageField(upload_to='media')),
                ('price', models.FloatField()),
                ('squarefoot', models.FloatField(default=100.0)),
                ('city', models.CharField(max_length=100)),
                ('town_address', models.CharField(max_length=100)),
                ('bedroom', models.IntegerField(default=2)),
                ('bedroom_img', models.ImageField(upload_to='media/bedroom_img')),
                ('kitchen_img', models.ImageField(upload_to='media/kichen_img')),
                ('kitchen', models.IntegerField(default=1)),
                ('let_bath', models.IntegerField(default=2)),
                ('swimming_pool', models.ImageField(upload_to='media/swim_pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=10)),
                ('addhar_no', models.CharField(max_length=12)),
                ('profession', models.CharField(max_length=50)),
                ('rent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('comment_date', models.DateTimeField(auto_now=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
